#!/usr/bin/env bash
# Generate a local .env.local with secure secrets for development/testing.
# This file is intended for local use only and should NOT be committed.

set -euo pipefail

OUT_FILE=".env.local"

echo "Generating ${OUT_FILE} (will overwrite if exists)"

NEXTAUTH_SECRET=$(openssl rand -hex 32)
SYNC_TOKEN=$(openssl rand -hex 32)
ADMIN_PASS=$(openssl rand -base64 24)

cat > ${OUT_FILE} <<EOF
# Local environment for Prohesis (autogenerated)
# DO NOT COMMIT THIS FILE
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
# Postgres connection string - replace the placeholder with your DB credentials
DATABASE_URL=postgres://postgres:password@localhost:5432/prohesis_dev
# RPC endpoint for Sepolia (or other chain)
SEPOLIA_RPC_URL=https://sepolia.infura.io/v3/YOUR_INFURA_KEY
# Factory contract address (client-visible)
NEXT_PUBLIC_FACTORY_CONTRACT=0x0000000000000000000000000000000000000000
SYNC_TOKEN=${SYNC_TOKEN}
ADMIN_USER=admin@example.com
ADMIN_PASS=${ADMIN_PASS}
EOF

chmod 600 ${OUT_FILE}
echo "Wrote ${OUT_FILE} (keep it secret)."
echo "NEXTAUTH_SECRET and SYNC_TOKEN generated. Edit DATABASE_URL, SEPOLIA_RPC_URL, NEXT_PUBLIC_FACTORY_CONTRACT as needed."
