name: Sync Factory to DB

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install
        run: |
          npm ci

      - name: Run sync script
        env:
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          NEXT_PUBLIC_SEPOLIA_RPC_URL: ${{ secrets.NEXT_PUBLIC_SEPOLIA_RPC_URL }}
          NEXT_PUBLIC_FACTORY_CONTRACT: ${{ secrets.NEXT_PUBLIC_FACTORY_CONTRACT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          node scripts/syncFactoryToDb.mjs
